apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostad-ui
  namespace: shaddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ostad-ui
  template:
    metadata:
      labels:
        app: ostad-ui
    spec:
      containers:
        - name: ostad-ui
          image: shaddy/ostad-ui:latest
          imagePullPolicy: Never 
          ports:
            - containerPort: 5173
