apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostad-server
  namespace: shaddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ostad-server
  template:
    metadata:
      labels:
        app: ostad-server
    spec:
      containers:
        - name: ostad-server
          image: shaddy/ostad-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
